### ISSUE TITLE
S3 Bucket Fails to Create Due to Missing ObjectOwnership

### ISSUE THREAD

**Issue by oktab1** [aws-samples/amazon-eks-inter-az-traffic-visibility#12]
```
11:57:08 AM | CREATE_FAILED        | AWS::S3::Bucket                          | ServerAccessLogs48D8D751
Bucket cannot have ACLs set with ObjectOwnership's BucketOwnerEnforced setting (Service: Amazon S3; Status Code: 400; Error Code: InvalidBucketAclWithO
bjectOwnership; Request ID: 1Y8MKVTBJ67WM4D9; S3 Extended Request ID: KWuGXVNqRylG2LSLGHg7JwdUEsalgRGAMBXqyWuGoOIX7sqd1r3shHW7K8ibGSXSZ8760I+t07dj3wcxb
Qnp2w==; Proxy: null)


 ❌  CdkEksInterAzVisibility failed: Error: The stack named CdkEksInterAzVisibility failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Bucket cannot have ACLs set with ObjectOwnership's BucketOwnerEnforced setting (Service: Amazon S3; Status Code: 400; Error Code: InvalidBucketAclWithObjectOwnership; Request ID: 1Y8MKVTBJ67WM4D9; S3 Extended Request ID: KWuGXVNqRylG2LSLGHg7JwdUEsalgRGAMBXqyWuGoOIX7sqd1r3shHW7K8ibGSXSZ8760I+t07dj3wcxbQnp2w==; Proxy: null)
    at FullCloudFormationDeployment.monitorDeployment (/Users/tolub/Documents/DevEnv/amazon-eks-inter-az-traffic-visibility/node_modules/aws-cdk/lib/index.js:380:10236)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async deployStack2 (/Users/tolub/Documents/DevEnv/amazon-eks-inter-az-traffic-visibility/node_modules/aws-cdk/lib/index.js:383:145458)
    at async /Users/tolub/Documents/DevEnv/amazon-eks-inter-az-traffic-visibility/node_modules/aws-cdk/lib/index.js:383:128776
    at async run (/Users/tolub/Documents/DevEnv/amazon-eks-inter-az-traffic-visibility/node_modules/aws-cdk/lib/index.js:383:126782)
```

**Comment by fibert** [comment]
The related PR was merged, closing this issue.
